server {
    listen 80;
    location /auth/ {
        proxy_pass http://auth:8000/;
    }
    location /catalog/ {
        proxy_pass http://catalog:8000/;
    }
    location /stats/ {
        proxy_pass http://stats:8000/;
    }
    location / {
        proxy_pass http://gateway:8000/;
    }
}
